version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - decorder
    - dogsled
    - dupword
    - errcheck
    - gocheckcompilerdirectives
    - gocritic
    - godot
    - goheader
    - gosec
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - misspell
    - nosprintfhostport
    - predeclared
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    gocritic:
      disabled-checks:
        - appendAssign
        - ifElseChain
        - singleCaseSwitch
    staticcheck:
      checks:
        - all
        - -QF1001
        - -ST1005
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
